### ISSUE TITLE
No Rproj file

### ISSUE THREAD

**Issue by denironyx** [MarketBridge/zctaCrosswalk#7]
I noticed the project repo don't have a R project file. Is there a reason why?

**Comment by denironyx** [comment]
Nevermind, I see you added a .Rproj to gitignore file. However, is there a reason why you don't want to push the Rproj file to code base?

**Comment by arilamstein** [comment]
I believe that I just did whatever RStudio did as a default when creating a new package. This was not a conscious decision on my part.

I actually have no idea whether there is a best practice around adding .Rproj files for R packages to github. Can you link to anything authoritative around this (e.g. from Hadley's book on R package development)?

**Comment by denironyx** [comment]
I don't believe there is anything authoritative around this, only developer preferences. I know packages like [`bs4dash`](https://github.com/RinteRface/bs4Dash) , [tidyverse](https://github.com/tidyverse/tidyverse) etc contains .Rproj file in it.

**Comment by denironyx** [comment]
I think for me it's easier for contributor to start the application in Rstudio directly from the .Rproj file as compared to create a new project file, etc.

Anyway, it's your call.

**Comment by alamstein** [comment]
I added it. See here, including my rational: https://github.com/MarketBridge/zctaCrosswalk/commit/4f4dd28ebbe636917236a349719ca937ced2ce1c
