### ISSUE TITLE
Probably want to remove " County" from county names

### ISSUE THREAD

**Issue by arilamstein** [MarketBridge/zctaCrosswalk#9]
It's an ongoing issue with no clear answer - to what extent, if any, should we modify data from the census bureau?

In my latest fork I'm experimenting with syntax like:

```
get_zctas_by_county(counties)
```

Where `counties` can be anything valid: `"06075"` (FIPS code), `6075` (FIPS code as numeric) and `"San Francisco County"` (the literal name of the county in the dataset). 

Presumably this is fine, but since just about every county ends in "County", and people are already calling a function with `county` in it, this might be superfluous. And so people might prefer if we drop that word from the dataset.

Also, in my fork, I'm now storing the states in all lowercase, and transforming the user input to all lower, so it becomes case insensitive. We might want to do that here too.

**Comment by alamstein** [comment]
This is moot because I dropped the ability to select zctas by county name. The reasoning is that there are many county names that appear in multiple states, so there's ambiguity. I'd rather force the user to select by fips code.
